# Site settings
title: Peter Compernolle
email: me@petercompernolle.com
description: > # this means to ignore newlines until "baseurl:"
  I make software and ride bikes in the greatest city on Earth.
baseurl: "" # the subpath of your site, e.g. /blog
root_url: "/" # the subpath of your site, e.g. /blog
url: "https://petercompernolle.com" # the base hostname & protocol for your site
twitter_username: thelowlypeon
github_username:  thelowlypeon
google_analytics: "UA-2133957-3"

collections:
  posts:
    output: true
    permalink: "/blog/:year/:title"
  projects:
    output: true
    permalink: "/projects/:name"

# Build settings
markdown: kramdown

gems:
  - jekyll-assets
